# Configuration for Rasa NLU.
language: en
# pipeline: supervised_embeddings
pipeline: pretrained_embeddings_spacy
# Configuration for Rasa Core.
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
